#!/bin/sh

KDE=0

[ -x /usr/bin/kdialog ] && KDE=1

if [ ! -x /usr/bin/mencoder ]; then
	[ $KDE -eq 1 ] && kdialog --title "No mencoder installed" --passivepopup "Uncompressed video is in the $1 directory." 10 &
	echo "No mencoder installed"
	exit 1
fi

if [ ${#} -ne 2 ]; then
	echo "Usage: $0 [src dir] [dst dir]"
	exit 2
fi

if [ ! -d "$1" -o ! -d "$2" ]; then
	echo "Source or destination directory doesn't exist."
	exit 3
fi

filename="$(ls $1/*.seom | head -1 2> /dev/null)"

if [ ! -e "$filename" ]; then
	echo "No .seom files in the $1 directory."
	exit 4
fi

tmpfn=$(mktemp $filename-$$-$RANDOM-XXXXXX)

mv -f "$filename" "$tmpfn"

[ $KDE -eq 1 ] && kdialog --passivepopup "Encoding video..." 3 &

dest="$2/$(basename $filename .seom)-$(date "+%y-%m-%d %H:%M:%S").avi"

seom-filter "$tmpfn" | mencoder - -ovc xvid -xvidencopts bitrate=1200 -o "$dest" ${OPT} 2>&1 >/dev/null

if [ $? -eq 0 ]; then
	[ $KDE -eq 1 ] && kdialog --title "Encoding successfull" --passivepopup "$dest done." 10 &
	echo "Encoding successfull."
	echo "$dest done."
	rm -f "$tmpfn"

	exit 0
else
	[ $KDE -eq 1 ] && kdialog --title "Encoding failed" --passivepopup "Uncompressed video is in the $1 directory." 10 &
	echo "Encoding failed."
	rm -f "$dest"

	exit 5
fi
